//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAcc.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FuelAccStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuelAccStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuelAcc.Localization.FuelAccStrings", typeof(FuelAccStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Button_Backup {
            get {
                return ResourceManager.GetString("Button_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Browser.
        /// </summary>
        public static string Button_Launch_Browser {
            get {
                return ResourceManager.GetString("Button_Launch_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Button_Post {
            get {
                return ResourceManager.GetString("Button_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process StopRussiaChannel targets.
        /// </summary>
        public static string Button_ProcessStopRussiaChannel {
            get {
                return ResourceManager.GetString("Button_ProcessStopRussiaChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Button_Reload {
            get {
                return ResourceManager.GetString("Button_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Button_Restore {
            get {
                return ResourceManager.GetString("Button_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Column_Date {
            get {
                return ResourceManager.GetString("Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Column_Error {
            get {
                return ResourceManager.GetString("Column_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Column_Id {
            get {
                return ResourceManager.GetString("Column_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Column_Parameters {
            get {
                return ResourceManager.GetString("Column_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Column_Profile {
            get {
                return ResourceManager.GetString("Column_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Column_Succeeded {
            get {
                return ResourceManager.GetString("Column_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Column_Type {
            get {
                return ResourceManager.GetString("Column_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Column_Url {
            get {
                return ResourceManager.GetString("Column_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want backup?.
        /// </summary>
        public static string Confirm_Backup {
            get {
                return ResourceManager.GetString("Confirm_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to backup selected profile?.
        /// </summary>
        public static string Confirm_Backup_Profile {
            get {
                return ResourceManager.GetString("Confirm_Backup_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to CLEAR selected profile?.
        /// </summary>
        public static string Confirm_Clear_Profile {
            get {
                return ResourceManager.GetString("Confirm_Clear_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ure you want to delete?.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to restore over selected profile? All existed data will be lost!.
        /// </summary>
        public static string Confirm_Restore_Profile {
            get {
                return ResourceManager.GetString("Confirm_Restore_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want save?.
        /// </summary>
        public static string Confirm_Save {
            get {
                return ResourceManager.GetString("Confirm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit browser script.
        /// </summary>
        public static string Edit_Script_Browser {
            get {
                return ResourceManager.GetString("Edit_Script_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit generic script.
        /// </summary>
        public static string Edit_Script_Generic {
            get {
                return ResourceManager.GetString("Edit_Script_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Telegram script.
        /// </summary>
        public static string Edit_Script_Telegram {
            get {
                return ResourceManager.GetString("Edit_Script_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Field_Code {
            get {
                return ResourceManager.GetString("Field_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Field_PhoneNumber {
            get {
                return ResourceManager.GetString("Field_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Field_Text {
            get {
                return ResourceManager.GetString("Field_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 10 reported events with realtime update..
        /// </summary>
        public static string Page_Events_Intro {
            get {
                return ResourceManager.GetString("Page_Events_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Page_Events_Nav {
            get {
                return ResourceManager.GetString("Page_Events_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Page_Events_Title {
            get {
                return ResourceManager.GetString("Page_Events_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Home_Nav {
            get {
                return ResourceManager.GetString("Page_Home_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can report single URL by manually fill the form.
        /// </summary>
        public static string Page_Report_Intro {
            get {
                return ResourceManager.GetString("Page_Report_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Page_Report_Nav {
            get {
                return ResourceManager.GetString("Page_Report_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report URL.
        /// </summary>
        public static string Page_Report_Title {
            get {
                return ResourceManager.GetString("Page_Report_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can report many URLs by just paste a text (as an example from a Telegram post) and the server will recognize all supported URL types in the text automatically..
        /// </summary>
        public static string Page_ReportRaw_Intro {
            get {
                return ResourceManager.GetString("Page_ReportRaw_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report text.
        /// </summary>
        public static string Page_ReportRaw_Nav {
            get {
                return ResourceManager.GetString("Page_ReportRaw_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Text.
        /// </summary>
        public static string Page_ReportRaw_Title {
            get {
                return ResourceManager.GetString("Page_ReportRaw_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to launch a browser once for log in into your social network accounts. 
        ///Supported YouTube, Facebook, Twitter, Instagram, TikTok. After you logged in to account of social network exit from the browser.
        /// </summary>
        public static string Settings_Browser_Form_Profiles_Intro {
            get {
                return ResourceManager.GetString("Settings_Browser_Form_Profiles_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage profiles.
        /// </summary>
        public static string Settings_Browser_Form_Profiles_Name {
            get {
                return ResourceManager.GetString("Settings_Browser_Form_Profiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser settings.
        /// </summary>
        public static string Settings_Browser_Title {
            get {
                return ResourceManager.GetString("Settings_Browser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email settings.
        /// </summary>
        public static string Settings_Email_Title {
            get {
                return ResourceManager.GetString("Settings_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex settings.
        /// </summary>
        public static string Settings_Regex_Title {
            get {
                return ResourceManager.GetString("Settings_Regex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacements settings.
        /// </summary>
        public static string Settings_Replacements_Title {
            get {
                return ResourceManager.GetString("Settings_Replacements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser scripts.
        /// </summary>
        public static string Settings_Scripts_Browser {
            get {
                return ResourceManager.GetString("Settings_Scripts_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic scripts.
        /// </summary>
        public static string Settings_Scripts_Generic {
            get {
                return ResourceManager.GetString("Settings_Scripts_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram scripts.
        /// </summary>
        public static string Settings_Scripts_Telegram {
            get {
                return ResourceManager.GetString("Settings_Scripts_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 15 min to sign in with sent code.
        /// </summary>
        public static string Settings_Telega_Form_Code_Hint {
            get {
                return ResourceManager.GetString("Settings_Telega_Form_Code_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code to phone.
        /// </summary>
        public static string Settings_Telega_Form_Code_Name {
            get {
                return ResourceManager.GetString("Settings_Telega_Form_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with phone and code.
        /// </summary>
        public static string Settings_Telega_Form_Sign_Name {
            get {
                return ResourceManager.GetString("Settings_Telega_Form_Sign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram settings.
        /// </summary>
        public static string Settings_Telega_Title {
            get {
                return ResourceManager.GetString("Settings_Telega_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted report messages.
        /// </summary>
        public static string Table_Posted {
            get {
                return ResourceManager.GetString("Table_Posted", resourceCulture);
            }
        }
    }
}
